name: github-actions-part-2-basics
env:
     EB_PACKGE_S3_BUCKET_NAME: arn:aws:s3:::my-flask-app-packages
     EB_APPLIVATION_NAME: "MyFlask"
     EB_ENVIROMENT_NAME: "MyFlask-env"
     DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"
     AWS_REGION_NAME: "us-east-1"

on:
     push        :
     pull_request:
      branches    : -master


jobs:
 
 my_ci_part:
   
    runs-on: ubuntu-latest

  
    steps:
      - name: Git clone our repo
        uses: Action/checkout@v1
      - name: Create Zip deploymant package
        run: zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x* .git*
        
        
      - name: Configure my AWS Credentials 
        uses: aws-actions/configure-aws-checkout@v1
        with: 
           aws-access-key-id    : ${{ secret.MY_AWS_ACCESS_KEY }}
           aws-secret_access-key: ${{ secret.MY_AWS_SECRET_KEY }}
           aws-region           : ${{ env.AWS_REGION_NAME }}
