#-------------------------
#GItHub Action Part-1-Basic
#
#Copyleft (c) by Denis Astahov 2019
#------------------------
# This is a basic workflow to help you get started with Actions

name: My-GitHubAction-Basics
env:
 
     APPLIVATION_NAME: "MyFlask"
     DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"

on:
     push        :
     pull_request:
      branches    : -master

  # Allows you to run this workflow manually from the Actions tab
     workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 my_testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print Hello Message
        run: echo "Hello world from Testing job"
      - name: Execute few commands
        run: |
         echo "Hello Messege1"
         echo "Hello Messege1"
         echo "Application name: ${{env.APPLIVATION_NAME }}"

         
      - name: List current foldor 
        run:  ls -la

      - name: git clone my repo 
        uses: actions/checkout@v1

      - name: List current foldor 
        run:  ls -la
      # Runs a set of commands using the runners shell
      - name: Print Hello Message
        run: echo "Hello world from Deploy job" 

 my_deploy:
        
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
     VAR1: "this is Job Level Varible1"
     VAR2: "this is Job Level Varible2"
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print Hello Message in Testing
        run: echo "Hello world from Testing job"
        
      - name: Print env vars 
        run: |
         echo "VAR1-${{env.VAR1}}"
         echo "VAR2-${{env.VAR2}}"
         echo "VAR3-$Local_var"
        env:
          Local_var: "This is Superr local Enviroment varibale"
        
     # Runs a set of commands using the runners shell
      - name: Print Hello Message in Deploy
        run: echo "Hello world from Deploy job" 
        
      - name: Printing Deploy package
        run : echo "Deploy package name is ${{env.DEPLOY_PACKAGE_NAME}}"
      - name: Let's test some packages iof the are here 1
        run: aws --version
        
      - name: Let's test some packages iof the are here 2
        run: zip --version
