#-------------------------
#GItHub Action Part-1-Basic
#
#Copyleft (c) by Denis Astahov 2019
#------------------------
name: My-GitHubAction-Basics

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello world from Testing"

  my_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello world from Deploy"
